name: Build and Release

on:
  push:
    branches:
      - main  # Build and release on pushes to the 'main' branch

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install wheel

      - name: Build the package
        run: |
          python setup.py sdist bdist_wheel

      - name: Create a GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.AUTH_GITHUB_TOKEN }}
        with:
          token: ${{ secrets.AUTH_GITHUB_TOKEN }}
          tag_name: latest
          draft: false
          prerelease: false
          name: Latest Release
          files: |
            dist/**.*